version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3334"  # External:Internal
    networks:
      custom_network:
        ipv4_address: 172.18.0.2

  nodejs:
    image: node:14
    container_name: nodejs_container
    working_dir: /app
    volumes:
      - ./app:/app
    command: "npm start"
    ports:
      - "5134:3000"  # External:Internal
    networks:
      custom_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - mysql
      

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
